---
- hosts: titoWebserver
  become: yes
  become_method: sudo
  vars:
    mapsapikey: AIzaSyCrpIQtxT14_s_DcjAQwUa5r1p1IaTO2eQ
  tasks:
      - name: Install apache package
        yum:
          name: httpd
          state: present
          
      - name: Install php 
        yum:
          name: php
          state: present
          
      - name: Install php-sql
        yum:
          name: php-mysql
          state: present
          
      - name: Install git 
        yum:
          name: git
          state: present
      
      - name: Start service httpd, if not started
        service:
          name: httpd
          state: started
          
      - name: Ensure SELinux is disabled
        lineinfile:
          path: /etc/selinux/config
          regexp: '^SELINUX='
          line: SELINUX=disabled
          
      - name: Clone tito git repository
        git:
          repo: https://github.com/vmeoc/Tito
          dest: /var/www/html
          clone: yes
          update: yes
          
      - name: Change Apache default page to index.php
        copy:
          dest: "/var/www/html/.htaccess"
          content: "DirectoryIndex index.php"

      - name: Set API gateway in index.php
        replace:
          path: /var/www/html/index.php
          regexp: 'API_GW'
          replace: "{{ mapsapikey }}"
          
      - name: Insert lines in HTTPD configuration file to ensure PHP is enabled and environment variable set
        blockinfile:
          path: /etc/httpd/conf/httpd.conf
          block: |
            LoadModule php5_module modules/libphp5.so
            <IfModule env_module>
               SetEnv TITO-SQL "{{ SQLSERVER }}"
            </IfModule>\
            
      - name: Insert lines in PHP.ini configuration file to set default timezone
        blockinfile:
          path: /etc/php.ini
          block: |
            date.timezone = Europe/London
            
      - name: Restart service httpd to pickup httpd.conf and php.ini changes
        service:
          name: httpd
          state: restarted

- hosts: titoDatabase
  become: yes
  become_method: sudo
  gather_facts: true
  vars:
    root_db_password: Tito2016
  tasks:
      - name: Ensure SELinux is disabled
        lineinfile:
          path: /etc/selinux/config
          regexp: '^SELINUX='
          line: SELINUX=disabled

      - name: Install MySQL 5.7 repo
        yum:
          name: http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm
          state: present

      - name: Install MySQL client
        yum:
          name: mysql
          state: present
          
      - name: Install MySQL server
        yum:
          name: mysql-server
          state: present
          
      - name: Start service mysqld
        service:
          name: mysqld
          state: started

      - name: Allow simple MySQL password
        shell: mysql -u root -p$(cat /var/log/mysqld.log | grep "temporary password" | rev | cut -d " " -f 1 | rev) -e "SET GLOBAL validate_password_policy=LOW;" --connect-expired-password

      - name: Reset the root@localhost password
        shell: mysql -u root -p$(cat /var/log/mysqld.log | grep "temporary password" | rev | cut -d " " -f 1 | rev) -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ root_db_password }}';" --connect-expired-password
        
      - name: Configure MySQL client
        copy:
          dest: "~/.my.cnf"
          content: |
            [mysql]
            user = 'root'
            password = '{{ root_db_password }}'
            
      - name: Install python pip
        yum:
          name: python-pip
          state: present

      - name: Install PyMySQL
        pip:
          name: PyMySQL
          state: present

      - name: Create TitoDB database
        mysql_db:
          name: TitoDB
          state: present
          login_user: root
          login_password: '{{ root_db_password }}'
        
      - name: Create DB setup file
        copy:
          dest: "/tmp/Tito.sql"
          content: |
            CREATE TABLE TitoTable (id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, home VARCHAR(50) NOT NULL, work VARCHAR(50) NOT NULL, hour_home_departure VARCHAR(50) NOT NULL, hour_work_departure VARCHAR(50) NOT NULL)

      - name: Create TitoDB TitoTable
        mysql_db:
          name: TitoDB
          state: import
          target: /tmp/Tito.sql
          login_user: root
          login_password: '{{ root_db_password }}'
